### ISSUE TITLE
Contribution to compressed texture list of tested hardware

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [Vinc3r/BJS-KTX-textures#1]
Hi,

I've been working on a small toolchain to ease the generation of compressed textures:
https://github.com/timvanScherpenzeel/texture-compressor

As part of the research I've created a support table of various hardware that might be useful for you
https://gist.github.com/TimvanScherpenzeel/3725c63bb41c9d7c92a76068dbd78d89

I've generated the support table from another tool that I wrote (in case you would like to verify the information): https://github.com/timvanScherpenzeel/detect-features. The raw data is available on https://github.com/TimvanScherpenzeel/detect-features/tree/master/data.

**Comment by Vinc3r** [comment]
Very interesting tool, thanks! I will take a look :)

**Comment by Vinc3r** [comment]
I have to take time to test and add link in my readme
